### PR TITLE
Supporting hazelcast multi nodes

### PR DESCRIPTION
**Pull request by sinwe**

### CODE REVIEW

**Comment by lptr** [comment]
@sinwe Would you be interested in taking over the maintenance of the Hazelcast plugin?

**Comment by sinwe** [comment]
@lptr I don't mind.
What do you propose to do that? You're giving me admin to the project? Or I fork and run it on my own?

**Comment by lptr** [comment]
That's great, because we don't currently have the bandwidth to maintain it. I would suggest you fork this repository, and then we can retire it. Let me check with Gradle to see if this is okay from a licensing perspective (I'm almost completely sure it is, but it's better to be safe).

**Comment by lptr** [comment]
I added the Apache 2.0 license (the same that we use for all our open-source projects). Please feel free to take it over from here in your fork! Please let me know where the fork lives on so I can link to it from the README of this repo.

**Comment by sinwe** [comment]
Thank you @lptr.
In term of package name, can I retain the original one?
For the artifact group, I'm sure I have to change as sonatype wouldn't allow me to use org.gradle.

Also, how to do release with this repo?

**Comment by lptr** [comment]
That's a good point. I think it would be best to keep the group name and package name in sync, so I'd say you should change both to your own.

Can you maybe join our community Slack channel? It would be easier to discuss this there. https://gradle-community.slack.com/

**Comment by sinwe** [comment]
I'll change the package and group name accordingly.

**Comment by sinwe** [comment]
@lptr I've forked it and it now lives at https://github.com/sinwe/gradle-hazelcast-plugin

**Comment by lptr** [comment]
I've added a link in the readme. Please consider joining the Gradle community Slack to continue the conversation. And thanks again for taking this over.

**Pull request closed without merging**
